AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3Bucket:
    Description: The name of the S3 bucket that contains the source artifact
    Type: String
  SourceS3Key:
    Description: The file name of the source artifact, such as myfolder/myartifact.zip
    Type: String
  EBProdCNAME:
    Type: String
    Description: "CNAME of Production EB environment"
  EBTestCNAME:
    Type: String
    Description: "CNAME of Test EB environment"
  EBProdAppName:
    Type: String
    Description: "EB application name for production"
  EBProdEnvName:
    Type: String
    Description: "EB environment name for production"
  EBTestAppName:
    Type: String
    Description: "EB application name for test"
  EBTestEnvName:
    Type: String
    Description: "EB environment name for test"
  ProdInstanceType:
    Type: String
    Description: "Specify instance type"
  TestInstanceType:
    Type: String
    Description: "Specify instance type"
  LBHealthCheckPath:
    Type: String
    Description: "Healt check path for load balancers"
  EBPlatform:
    Type: String
    Description: SolutionStackName for Elastic Beanstalk

Resources:
  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"
      RoleName: ebs-instance-profile-role

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref 'InstanceProfileRole'
      InstanceProfileName: ebs-ec2-instance-profile

  EBProdApp:
   Type: AWS::ElasticBeanstalk::Application
   Properties:
      ApplicationName: !Ref EBProdAppName
      Description: Elastic Beanstalk Production Application

  EBProdAppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
       ApplicationName: !Ref EBProdApp
       SourceBundle:
           S3Bucket: !Ref S3Bucket
           S3Key: !Ref SourceS3Key

  EBTestApp:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
       ApplicationName: !Ref EBTestAppName
       Description: Elastic Beanstalk Test Application

  EBTestAppVersion:
   Type: AWS::ElasticBeanstalk::ApplicationVersion
   Properties:
      ApplicationName: !Ref EBTestApp
      SourceBundle:
          S3Bucket: !Ref S3Bucket
          S3Key: !Ref SourceS3Key

  EBProdEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref EBProdApp
      Description: "Production environment"
      EnvironmentName: !Ref EBProdEnvName
      CNAMEPrefix: !Ref EBProdCNAME
      SolutionStackName: !Ref EBPlatform
      VersionLabel: !Ref EBProdAppVersion
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref EC2InstanceProfile
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: InstanceType
          Value: !Ref ProdInstanceType
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: LoadBalancerType
          Value: application
        - Namespace : "aws:elasticbeanstalk:environment:process:default"
          OptionName : HealthCheckPath
          Value : !Ref LBHealthCheckPath
        - Namespace : "aws:elasticbeanstalk:command"
          OptionName: "DeploymentPolicy"
          Value     : "Rolling"
        - Namespace : "aws:elasticbeanstalk:command"
          OptionName: "BatchSizeType"
          Value     : "Fixed"
        - Namespace : "aws:elasticbeanstalk:command"
          OptionName: "BatchSize"
          Value     : "1"
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: '2'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: '4'

  EBTestEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref EBTestApp
      Description: "Test Environment"
      EnvironmentName: !Ref EBTestEnvName
      CNAMEPrefix: !Ref EBTestCNAME
      SolutionStackName: !Ref EBPlatform
      VersionLabel: !Ref EBTestAppVersion
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref EC2InstanceProfile
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: InstanceType
          Value: !Ref TestInstanceType
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: LoadBalancerType
          Value: application
        - Namespace : "aws:elasticbeanstalk:environment:process:default"
          OptionName : HealthCheckPath
          Value : !Ref LBHealthCheckPath
